import fs from "node:fs/promises";
import path from "node:path";

import type { KnowledgeBasePluginConfig } from "../types.js";
import { atomicWriteText } from "./atomic-write.js";
import { parseOutputNoteMarkdown, parseSourceNoteMarkdown } from "./frontmatter.js";
import { getVaultPaths, resolveVaultPath } from "./paths.js";

type SourceIndexEntry = {
  id: string;
  notePath: string;
  title: string;
  rawPath: string;
  updatedAt: string;
};

type OutputIndexEntry = {
  id: string;
  notePath: string;
  title: string;
  query: string;
  sourceRefs: string[];
  updatedAt: string;
};

async function readMarkdownFiles(
  config: KnowledgeBasePluginConfig,
  relativeDir: string,
): Promise<Array<{ path: string; content: string }>> {
  const absoluteDir = await resolveVaultPath(config, relativeDir);

  try {
    const entries = await fs.readdir(absoluteDir, { withFileTypes: true });
    const files = entries
      .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
      .map((entry) => `${relativeDir}/${entry.name}`)
      .sort();

    const items: Array<{ path: string; content: string }> = [];
    for (const relativePath of files) {
      const absolutePath = await resolveVaultPath(config, relativePath);
      items.push({
        path: relativePath,
        content: await fs.readFile(absolutePath, "utf8"),
      });
    }

    return items;
  } catch {
    return [];
  }
}

async function collectSourceEntries(config: KnowledgeBasePluginConfig): Promise<SourceIndexEntry[]> {
  const sourceFiles = await readMarkdownFiles(config, getVaultPaths(config).sources);

  return sourceFiles.map(({ path: notePath, content }) => {
    const { frontmatter } = parseSourceNoteMarkdown(content);
    return {
      id: frontmatter.id,
      notePath,
      title: frontmatter.title,
      rawPath: frontmatter.raw_path,
      updatedAt: frontmatter.updated_at,
    };
  });
}

async function collectOutputEntries(config: KnowledgeBasePluginConfig): Promise<OutputIndexEntry[]> {
  const outputFiles = await readMarkdownFiles(config, getVaultPaths(config).outputs);

  return outputFiles.map(({ path: notePath, content }) => {
    const { frontmatter } = parseOutputNoteMarkdown(content);
    return {
      id: frontmatter.id,
      notePath,
      title: frontmatter.title,
      query: frontmatter.query,
      sourceRefs: frontmatter.source_refs,
      updatedAt: frontmatter.updated_at,
    };
  });
}

function buildSourcesIndexMarkdown(indexDir: string, entries: SourceIndexEntry[]): string {
  const lines = [
    "# Sources Index",
    "",
    "Generated by `kb_rebuild_indexes`.",
    "",
  ];

  if (entries.length === 0) {
    lines.push("_No source notes yet._");
    return `${lines.join("\n")}\n`;
  }

  for (const entry of entries.sort((a, b) => a.id.localeCompare(b.id))) {
    const relativeLink = path.posix.relative(indexDir, entry.notePath);
    lines.push(
      `- [${entry.title}](${relativeLink}) (\`${entry.id}\`) - raw: \`${entry.rawPath}\` - updated: ${entry.updatedAt}`,
    );
  }

  return `${lines.join("\n")}\n`;
}

function buildOutputsIndexMarkdown(indexDir: string, entries: OutputIndexEntry[]): string {
  const lines = [
    "# Outputs Index",
    "",
    "Generated by `kb_rebuild_indexes`.",
    "",
  ];

  if (entries.length === 0) {
    lines.push("_No output notes yet._");
    return `${lines.join("\n")}\n`;
  }

  for (const entry of entries.sort((a, b) => a.id.localeCompare(b.id))) {
    const relativeLink = path.posix.relative(indexDir, entry.notePath);
    const sourceRefs = entry.sourceRefs.join(", ");
    lines.push(
      `- [${entry.title}](${relativeLink}) (\`${entry.id}\`) - query: ${entry.query} - sources: ${sourceRefs} - updated: ${entry.updatedAt}`,
    );
  }

  return `${lines.join("\n")}\n`;
}

export async function rebuildIndexes(config: KnowledgeBasePluginConfig): Promise<string[]> {
  const paths = getVaultPaths(config);
  const sourcesIndexPath = `${paths.indexes}/sources.md`;
  const outputsIndexPath = `${paths.indexes}/outputs.md`;

  const [sourceEntries, outputEntries] = await Promise.all([
    collectSourceEntries(config),
    collectOutputEntries(config),
  ]);

  await atomicWriteText(
    await resolveVaultPath(config, sourcesIndexPath),
    buildSourcesIndexMarkdown(paths.indexes, sourceEntries),
  );
  await atomicWriteText(
    await resolveVaultPath(config, outputsIndexPath),
    buildOutputsIndexMarkdown(paths.indexes, outputEntries),
  );

  return [sourcesIndexPath, outputsIndexPath];
}
